
package net.conselldemallorca.helium.integracio.tramitacio;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-04-22T09:15:26.220+02:00
 * Generated source version: 3.0.0-milestone2
 */

@WebFault(name = "TramitacioException", targetNamespace = "http://tramitacio.integracio.helium.conselldemallorca.net/")
public class TramitacioException_Exception extends Exception {
    
    private net.conselldemallorca.helium.integracio.tramitacio.TramitacioException tramitacioException;

    public TramitacioException_Exception() {
        super();
    }
    
    public TramitacioException_Exception(String message) {
        super(message);
    }
    
    public TramitacioException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TramitacioException_Exception(String message, net.conselldemallorca.helium.integracio.tramitacio.TramitacioException tramitacioException) {
        super(message);
        this.tramitacioException = tramitacioException;
    }

    public TramitacioException_Exception(String message, net.conselldemallorca.helium.integracio.tramitacio.TramitacioException tramitacioException, Throwable cause) {
        super(message, cause);
        this.tramitacioException = tramitacioException;
    }

    public net.conselldemallorca.helium.integracio.tramitacio.TramitacioException getFaultInfo() {
        return this.tramitacioException;
    }
}
